CREATE TABLE IF NOT EXISTS Actors        
(
    id int AUTO_INCREMENT PRIMARY KEY,
    firstname NVARCHAR(64) NOT NULL,
    lastname NVARCHAR(64) NOT NULL,
    bio NVARCHAR(4096),
    rating float
)            
     
INSERT INTO Actors (id,firstname, lastname, bio, rating) VALUES
(1,'Marlon', 'Brando', 'Iconic American actor known for his role in The Godfather, a pioneer of method acting.', 9.7),
('Al', 'Pacino', 'Legendary actor renowned for his intense performances in The Godfather, among other classics.', 9.6),
('James', 'Caan', 'Acclaimed actor best known for his role in The Godfather, bringing charismatic grit to the screen.', 9.4),
('Robert', 'Duvall', 'Veteran actor with memorable performances in The Godfather, delivering subtle yet powerful portrayals.', 9.3),
('Diane', 'Keaton', 'Beloved actress celebrated for her role in The Godfather, blending elegance with drama.', 9.2),
('Talia', 'Shire', 'Notable actress recognized for her role in The Godfather, adding depth to familial dynamics.', 9.0),
('Christian', 'Bale', 'Dynamic actor known for immersing himself in roles, notably in The Dark Knight and The Prestige.', 9.5),
('Heath', 'Ledger', 'Exceptional actor whose performance in The Dark Knight redefined comic book villainy.', 9.8),
('Aaron', 'Eckhart', 'Versatile actor remembered for his role in The Dark Knight, exuding a calm intensity.', 8.9),
('Michael', 'Caine', 'Distinguished actor with a career spanning decades, notably in The Dark Knight and Interstellar.', 9.0),
('Gary', 'Oldman', 'Transformative actor known for his chameleon-like roles, including a standout performance in The Dark Knight.', 9.1),
('Morgan', 'Freeman', 'Renowned actor with a commanding presence, featuring prominently in The Dark Knight and Se7en.', 9.4),
('Liam', 'Neeson', 'Powerful actor noted for his role in Schindler\'s List, bringing gravitas to historical drama.', 9.0),
('Henry', 'Fonda', 'Esteemed actor whose performance in 12 Angry Men remains a benchmark in cinematic history.', 9.2),
('Ian', 'McKellen', 'Legendary actor celebrated for his roles in The Lord of the Rings series as Gandalf.', 9.7),
('Viggo', 'Mortensen', 'Captivating actor known for his rugged portrayal of Aragorn in The Lord of the Rings: The Return of the King.', 9.3),
('Sean', 'Astin', 'Beloved actor recognized for his role as Samwise Gamgee in The Lord of the Rings series.', 9.0),
('Orlando', 'Bloom', 'Charismatic actor best known for his role as Legolas in The Lord of the Rings series.', 9.1),
('Cate', 'Blanchett', 'Award-winning actress whose performance as Galadriel in The Lord of the Rings series is legendary.', 9.4),
('John', 'Travolta', 'Iconic actor celebrated for his role in Pulp Fiction, embodying cool and chaos in one performance.', 8.8),
('Samuel', 'L. Jackson', 'Dynamic actor known for his commanding voice and memorable role in Pulp Fiction.', 9.2),
('Uma', 'Thurman', 'Stylish actress renowned for her transformative role in Pulp Fiction, combining allure with intensity.', 8.9),
('Bruce', 'Willis', 'Versatile actor who delivered an unforgettable performance in Pulp Fiction, adding raw energy to the film.', 8.7),
('Ving', 'Rhames', 'Respected actor known for his powerful presence in Pulp Fiction, leaving a lasting impact on audiences.', 8.8),
('Clint', 'Eastwood', 'Legendary actor known for his iconic role in The Good, the Bad and the Ugly, embodying rugged masculinity.', 9.0),
('Lee', 'Van Cleef', 'Renowned actor celebrated for his striking performance in The Good, the Bad and the Ugly as the menacing “Bad”.', 8.9),
('Eli', 'Wallach', 'Memorable actor whose role in The Good, the Bad and the Ugly showcased his unique blend of charm and menace.', 8.7),
('Tom', 'Hanks', 'Beloved actor known for his compelling performances in Forrest Gump, Saving Private Ryan, and The Green Mile.', 9.5),
('Robin', 'Wright', 'Talented actress celebrated for her role in Forrest Gump, bringing warmth and depth to her character.', 8.9),
('Gary', 'Sinise', 'Acclaimed actor recognized for his heartfelt portrayal in Forrest Gump, elevating every scene he graced.', 8.8),
('Brad', 'Pitt', 'Charismatic actor whose diverse roles, including in Fight Club, have left an indelible mark on modern cinema.', 9.0),
('Edward', 'Norton', 'Impressive actor known for his transformative roles in Fight Club and American History X, bringing intensity and nuance.', 9.1),
('Helena', 'Bonham Carter', 'Eccentric actress celebrated for her dynamic and unforgettable role in Fight Club.', 8.7),
('Leonardo', 'DiCaprio', 'Acclaimed actor known for his compelling performances in Inception, The Departed, and Django Unchained.', 9.4),
('Joseph', 'Gordon-Levitt', 'Versatile actor recognized for his role in Inception, effortlessly transitioning between drama and action.', 8.8),
('Elliot', 'Page', 'Breakthrough actor celebrated for his innovative performance in Inception, leaving a lasting impression.', 8.9),
('Mark', 'Hamill', 'Iconic actor best known for his legendary portrayal of Luke Skywalker in Star Wars: Episode V - The Empire Strikes Back.', 9.0),
('Harrison', 'Ford', 'Beloved actor known for his adventures in Star Wars: Episode V - The Empire Strikes Back, epitomizing heroic charm.', 9.2),
('Carrie', 'Fisher', 'Cult favorite actress celebrated for her role as Princess Leia in Star Wars: Episode V - The Empire Strikes Back.', 9.1),
('Billy', 'Dee Williams', 'Notable actor whose performance in Star Wars: Episode V - The Empire Strikes Back remains iconic.', 8.8),
('Keanu', 'Reeves', 'Cult actor known for his groundbreaking role in The Matrix, blending stoicism with action-packed flair.', 9.3),
('Laurence', 'Fishburne', 'Respected actor celebrated for his role in The Matrix, delivering powerful and memorable performances.', 9.0),
('Carrie-Anne', 'Moss', 'Dynamic actress recognized for her pioneering role in The Matrix, symbolizing strength and resilience.', 9.0),
('Robert', 'De Niro', 'Legendary actor known for his stellar performance in Goodfellas, exemplifying method acting at its best.', 9.5),
('Ray', 'Liotta', 'Renowned actor celebrated for his performance in Goodfellas, immersing audiences in the world of organized crime.', 9.0),
('Joe', 'Pesci', 'Acclaimed actor with a distinctive style, known for his unforgettable role in Goodfellas.', 8.9),
('Jack', 'Nicholson', 'Iconic actor whose brilliant performance in One Flew Over the Cuckoo\'s Nest and The Shining has defined a generation.', 9.4),
('Louise', 'Fletcher', 'Standout actress celebrated for her award-winning role in One Flew Over the Cuckoo\'s Nest.', 8.7),
('Toshirô', 'Mifune', 'Legendary actor known for his powerhouse performances in classic films like Seven Samurai.', 9.3),
('Takashi', 'Shimura', 'Acclaimed actor celebrated for his role in Seven Samurai, leaving an enduring legacy in cinema.', 9.1),
('Kevin', 'Spacey', 'Notable actor known for his compelling performances in Se7en and The Usual Suspects, marked by his unique intensity.', 8.8),
('James', 'Stewart', 'Beloved actor whose timeless performance in It\'s a Wonderful Life continues to inspire generations.', 9.5),
('Donna', 'Reed', 'Cherished actress celebrated for her role in It\'s a Wonderful Life, embodying warmth and sincerity.', 8.8),
('Anthony', 'Hopkins', 'Legendary actor known for his chilling performance in The Silence of the Lambs, leaving audiences spellbound.', 9.6),
('Jodie', 'Foster', 'Acclaimed actress celebrated for her riveting role in The Silence of the Lambs, blending vulnerability with strength.', 9.0),
('Matt', 'Damon', 'Versatile actor recognized for his captivating role in Saving Private Ryan, showcasing heroism amidst chaos.', 9.2),
('Tom', 'Sizemore', 'Notable actor known for his intense performance in Saving Private Ryan, adding depth to a war epic.', 8.7),
('Alexandre', 'Rodrigues', 'Talented actor celebrated for his authentic portrayal in City of God, bringing raw energy to the screen.', 8.9),
('Leandro', 'Firmino', 'Dynamic actor known for his gripping performance in City of God, highlighting urban narratives.', 8.8),
('Roberto', 'Benigni', 'Charismatic actor celebrated for his heartwarming and humorous performance in Life Is Beautiful.', 9.1),
('Nicoletta', 'Braschi', 'Beloved actress known for her role in Life Is Beautiful, adding emotional depth to the bittersweet narrative.', 8.8),
('Michael', 'Clarke Duncan', 'Imposing actor celebrated for his memorable performance in The Green Mile, leaving an indelible mark.', 9.0),
('Sam', 'Rockwell', 'Versatile actor known for his captivating work in The Green Mile, blending humor with gravitas.', 8.9),
('Matthew', 'McConaughey', 'Dynamic actor renowned for his leading role in Interstellar, exploring the depths of space and human emotion.', 9.2),
('Anne', 'Hathaway', 'Acclaimed actress celebrated for her performance in Interstellar, combining elegance with strength.', 9.0),
('Jessica', 'Chastain', 'Talented actress known for her compelling role in Interstellar, delivering a performance full of nuance.', 8.8),
('Rumi', 'Hiiragi', 'Cherished voice actress celebrated for her role in Spirited Away, enchanting audiences with her performance.', 8.9),
('Song', 'Kang-ho', 'Renowned actor celebrated for his standout performance in Parasite, capturing complex social realities.', 9.3),
('Lee', 'Sun-kyun', 'Acclaimed actor known for his role in Parasite, delivering a performance that resonates powerfully.', 8.8),
('Cho', 'Yeo-jeong', 'Dynamic actress celebrated for her compelling role in Parasite, contributing essential depth to the narrative.', 8.7),
('Jean', 'Reno', 'Iconic actor known for his cool and calm performance in Léon: The Professional, leaving a lasting impression.', 9.0),
('Natalie', 'Portman', 'Award-winning actress celebrated for her breakout role in Léon: The Professional, showcasing immense talent.', 9.1),
('Gabriel', 'Byrne', 'Notable actor known for his captivating performance in The Usual Suspects, adding layers to the mystery.', 8.9),
('Benicio', 'Del Toro', 'Acclaimed actor renowned for his role in The Usual Suspects, leaving audiences intrigued with his performance.', 9.0),
('Tatsuya', 'Nakadai', 'Legendary actor celebrated for his powerful performance in Harakiri, a classic of Japanese cinema.', 9.1),
('Matthew', 'Broderick', 'Cherished actor known for his endearing voice role as Simba in The Lion King.', 8.8),
('James', 'Earl Jones', 'Iconic voice actor celebrated for lending his deep resonant voice to The Lion King, defining a generation.', 9.3),
('Michael', 'J. Fox', 'Beloved actor renowned for his role in Back to the Future, capturing hearts with his charm.', 9.0),
('Christopher', 'Lloyd', 'Dynamic actor celebrated for his iconic performance in Back to the Future, delivering memorable moments.', 9.1),
('Lea', 'Thompson', 'Acclaimed actress known for her role in Back to the Future, embodying the spirit of adventure.', 8.9),
('Adrien', 'Brody', 'Distinguished actor celebrated for his compelling performance in The Pianist, delivering a haunting portrayal.', 9.2),
('Arnold', 'Schwarzenegger', 'Iconic actor known for his powerhouse role in Terminator 2: Judgment Day, defining action cinema.', 9.0),
('Linda', 'Hamilton', 'Notable actress celebrated for her strong portrayal in Terminator 2: Judgment Day, becoming an action icon.', 8.9),
('Russell', 'Crowe', 'Charismatic actor recognized for his commanding presence in Gladiator, delivering an unforgettable performance.', 9.3),
('Joaquin', 'Phoenix', 'Powerful actor celebrated for his compelling role in Gladiator, showcasing versatility in his craft.', 9.1),
('Mark', 'Wahlberg', 'Dynamic actor known for his role in The Departed, bringing intensity and authenticity to the screen.', 8.8),
('Hugh', 'Jackman', 'Versatile actor celebrated for his magnetic performance in The Prestige, blending showmanship with depth.', 9.0),
('Miles', 'Teller', 'Captivating actor known for his breakthrough performance in Whiplash, embodying passion and determination.', 8.9),
('J.K.', 'Simmons', 'Award-winning actor renowned for his commanding presence in Whiplash, delivering a masterclass in performance.', 9.2),
('François', 'Cluzet', 'Cherished actor celebrated for his heartfelt performance in The Intouchables, capturing human vulnerability.', 8.8),
('Omar', 'Sy', 'Dynamic actor known for his charismatic role in The Intouchables, bringing warmth and humor to the screen.', 9.0),
('Ulrich', 'Mühe', 'Acclaimed actor recognized for his riveting performance in The Lives of Others, embodying intensity and realism.', 9.1),
('Tsutomu', 'Tatsumi', 'Notable voice actor celebrated for his poignant performance in Grave of the Fireflies, touching hearts deeply.', 8.8),
('Ayano', 'Maeda', 'Renowned voice actress known for her heartwarming role in Grave of the Fireflies, a timeless piece of cinema.', 8.9),
('Humphrey', 'Bogart', 'Legendary actor celebrated for his iconic performance in Casablanca, a true hallmark of classic cinema.', 9.4),
('Ingrid', 'Bergman', 'Timeless actress renowned for her role in Casablanca, embodying elegance and strength.', 9.0),
('Philippe', 'Noiret', 'Distinguished actor celebrated for his role in Cinema Paradiso, capturing the magic of film through his performance.', 8.8),
('Enzo', 'Cannavale', 'Acclaimed actor known for his authentic portrayal in Cinema Paradiso, adding depth to a cinematic masterpiece.', 8.7),
('Sigourney', 'Weaver', 'Iconic actress celebrated for her groundbreaking performance in Alien, pioneering strong female roles in sci-fi.', 9.0),
('Robert', 'Downey Jr.', 'Charismatic actor celebrated for his pivotal role in Avengers: Infinity War, embodying wit and determination.', 9.2);
'

CREATE TABLE IF NOT EXISTS Movies        
(
    id int AUTO_INCREMENT PRIMARY KEY,
    title NVARCHAR(256) NOT NULL,
    year int NOT NULL,
    description NVARCHAR(4096),
    rating float
)            
   
INSERT INTO Movies (Title, Year, Description, Rating) VALUES
('The Godfather', 1972, 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 9.2),
('The Dark Knight', 2008, 'Batman faces the Joker, a criminal mastermind who seeks to plunge Gotham City into anarchy.', 9.0),
('Schindler\'s List', 1993, 'In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce.', 9.0),
('12 Angry Men', 1957, 'A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.', 9.0),
('The Lord of the Rings: The Return of the King', 2003, 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to distract him while Frodo brings the Ring to Mount Doom.', 9.0),
('Pulp Fiction', 1994, 'The lives of two mob hitmen, a boxer, a gangster\'s wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 8.9),
('The Good, the Bad and the Ugly', 1966, 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold.', 8.8),
('Forrest Gump', 1994, 'The presidencies of Kennedy and Johnson, Vietnam, Watergate, and other history unfold through the perspective of an Alabama man with a low IQ.', 8.8),
('Fight Club', 1999, 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.', 8.8),
('Inception', 2010, 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.', 8.8),
('The Lord of the Rings: The Fellowship of the Ring', 2001, 'A meek Hobbit and eight companions set out on a journey to destroy a powerful ring and save Middle-earth.', 8.8),
('Star Wars: Episode V - The Empire Strikes Back', 1980, 'After the Rebels are brutally overpowered, Luke Skywalker begins Jedi training with Yoda.', 8.7),
('The Matrix', 1999, 'A computer hacker learns about the true nature of his reality and his role in the war against its controllers.', 8.7),
('Goodfellas', 1990, 'The story of Henry Hill and his life in the mob, covering his relationship with his wife and mob partners.', 8.7),
('One Flew Over the Cuckoo\'s Nest', 1975, 'A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse.', 8.7),
('Seven Samurai', 1954, 'A poor village hires seven samurai to protect them from bandits.', 8.6),
('Se7en', 1995, 'Two detectives hunt a serial killer who uses the seven deadly sins as his motives.', 8.6),
('It\'s a Wonderful Life', 1946, 'An angel is sent from Heaven to help a desperately frustrated businessman.', 8.6),
('The Silence of the Lambs', 1991, 'A young FBI cadet must confide in an incarcerated killer to catch another serial killer.', 8.6),
('Saving Private Ryan', 1998, 'U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.', 8.6),
('City of God', 2002, 'Two boys growing up in a violent neighborhood of Rio de Janeiro take different paths.', 8.6),
('Life Is Beautiful', 1997, 'When an open-minded Jewish librarian and his son become victims of the Holocaust, he uses humor to protect his son.', 8.6),
('The Green Mile', 1999, 'The lives of guards on Death Row are affected by one of their charges who has a mysterious gift.', 8.6),
('Interstellar', 2014, 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.', 8.6),
('Spirited Away', 2001, 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods and spirits.', 8.6),
('Parasite', 2019, 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy and the destitute.', 8.5),
('Léon: The Professional', 1994, 'Mathilda, a 12-year-old girl, is reluctantly taken in by Léon, a professional assassin.', 8.5),
('The Usual Suspects', 1995, 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat.', 8.5),
('Harakiri', 1962, 'When an elder samurai requests to commit seppuku in a feudal lord\'s courtyard, he tells the story behind his tragic past.', 8.6),
('The Lion King', 1994, 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.', 8.5),
('Back to the Future', 1985, 'Marty McFly, a teenager, is accidentally sent 30 years into the past in a time-traveling DeLorean.', 8.5),
('The Pianist', 2002, 'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.', 8.5),
('Terminator 2: Judgment Day', 1991, 'A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her son.', 8.5),
('Gladiator', 2000, 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.', 8.5),
('American History X', 1998, 'A former neo-nazi tries to prevent his younger brother from going down the same wrong path.', 8.5),
('The Departed', 2006, 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang.', 8.5),
('The Prestige', 2006, 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion.', 8.5),
('Whiplash', 2014, 'A promising young drummer enrolls at a music conservatory where he is mentored by a brutal instructor.', 8.5),
('The Intouchables', 2011, 'After he becomes a quadriplegic, an aristocrat hires a young man from the projects to be his caregiver.', 8.5),
('The Lives of Others', 2006, 'In 1984 East Berlin, an agent of the secret police is assigned to spy on a writer and his lover.', 8.5),
('Grave of the Fireflies', 1988, 'A young boy and his little sister struggle to survive in Japan during World War II.', 8.5),
('Casablanca', 1942, 'A cynical American expatriate struggles to decide whether or not to help his former lover and her fugitive husband.', 8.5),
('Cinema Paradiso', 1988, 'A filmmaker recalls his childhood when he fell in love with the movies at his village\'s theater.', 8.5),
('Alien', 1979, 'After a space merchant vessel perceives an unknown transmission, one of the crew is attacked by a mysterious lifeform.', 8.5),
('Apocalypse Now', 1979, 'A U.S. Army officer is sent to assassinate a renegade Colonel who sees himself as a god.', 8.5),
('The Great Dictator', 1940, 'Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution.', 8.5),
('Sunset Blvd.', 1950, 'A screenwriter develops a dangerous relationship with a faded film star determined to make a triumphant return.', 8.4),
('Dr. Strangelove', 1964, 'An insane general triggers a path to nuclear holocaust that a war room of politicians and generals frantically tries to stop.', 8.4),
('Paths of Glory', 1957, 'After refusing to attack an enemy position, a General accuses his soldiers of cowardice and their commanding officer must defend them.', 8.4),
('The Shining', 1980, 'A family heads to an isolated hotel where an evil spiritual presence influences the father into violence.', 8.4),
('Django Unchained', 2012, 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner.', 8.4),
('WALL·E', 2008, 'In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that decides the fate of mankind.', 8.4),
('The Dark Knight Rises', 2012, 'Eight years after the Joker\'s reign, Batman returns to face the merciless terrorist Bane.', 8.4),
('Oldboy', 2003, 'After being kidnapped and imprisoned for 15 years, Oh Dae-Su is released and must find his captor in five days.', 8.4),
('Princess Mononoke', 1997, 'On a journey to find the cure for a curse, Ashitaka finds himself in the middle of a war between forest gods and humans.', 8.4),
('Avengers: Infinity War', 2018, 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos.', 8.4),
('Once Upon a Time in the West', 1968, 'A mysterious stranger joins forces with a notorious desperado to protect a widow from a ruthless assassin.', 8.5),
('Your Name.', 2016, 'Two teenagers share a profound connection when they suddenly start switching bodies.', 8.4),
('Coco', 2017, 'Aspiring musician Miguel enters the Land of the Dead to find his great-great-grandfather.', 8.4),
('3 Idiots', 2009, 'Two friends are searching for their long-lost companion. They recall their college days and how he inspired them.', 8.4),
('Toy Story 3', 2010, 'The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college.', 8.3),
('Braveheart', 1995, 'Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from tyranny.', 8.3),
('Amélie', 2001, 'Amélie is an innocent and naive girl in Paris with her own sense of justice.', 8.3),
('Up', 2009, '78-year-old Carl sets out to fulfill his dream to see the wilds of South America with a boy scout by accident.', 8.3); 


  CREATE TABLE IF NOT EXISTS ActorsMovies        
(
    id int AUTO_INCREMENT PRIMARY KEY,
    actorId int NOT NULL,
    movieId int NOT NULL,
    rolename NVARCHAR(64),
    FOREIGN KEY(actorId) REFERENCES Actors(id) ON DELETE CASCADE,
    FOREIGN KEY(movieId) REFERENCES Movies(id) ON DELETE CASCADE
);            


INSERT INTO ActorsMovies (actorId, movieId, rolename) VALUES
  (1, 1, 'Vito Corleone'),
  (2, 1, 'Michael Corleone'),
  (3, 1, 'Sonny Corleone'),
  (4, 1, 'Tom Hagen'),
  (5, 1, 'Kay Adams'),
  (6, 1, 'Connie Corleone'),
  (7, 2, 'Bruce Wayne / Batman'),
  (8, 2, 'Joker'),
  (9, 2, 'Harvey Dent'),
  (10, 2, 'Alfred Pennyworth'),
  (11, 2, 'Commissioner Gordon'),
  (12, 2, 'Lucius Fox'),
  (13, 3, 'Itzhak Stern'),
  (14, 4, 'Juror #8'),
  (15, 5, 'Gandalf'),
  (16, 5, 'Aragorn'),
  (17, 11, 'Samwise Gamgee'),
  (18, 11, 'Legolas'),
  (19, 11, 'Galadriel'),
  (20, 6, 'Vincent Vega'),
  (21, 6, 'Jules Winnfield'),
  (22, 6, 'Mia Wallace'),
  (23, 6, 'Butch Coolidge'),
  (24, 6, 'Marsellus Wallace'),
  (25, 7, 'Blondie'),
  (26, 7, 'Angel Eyes'),
  (27, 7, 'Tuco'),
  (28, 8, 'Forrest Gump'),
  (29, 8, 'Jenny Curran'),
  (30, 8, 'Lieutenant Dan Taylor'),
  (31, 9, 'Tyler Durden'),
  (32, 9, 'The Narrator'),
  (33, 9, 'Marla Singer'),
  (34, 10, 'Cobb'),
  (35, 10, 'Arthur'),
  (36, 10, 'Ariadne'),
  (37, 12, 'Luke Skywalker'),
  (38, 12, 'Han Solo'),
  (39, 12, 'Princess Leia'),
  (40, 12, 'Lando Calrissian'),
  (41, 13, 'Neo'),
  (42, 13, 'Morpheus'),
  (43, 13, 'Trinity'),
  (44, 14, 'Jimmy Conway'),
  (45, 14, 'Henry Hill'),
  (46, 14, 'Tommy DeVito'),
  (47, 15, 'Randle McMurphy'),
  (48, 15, 'Nurse Ratched'),
  (49, 16, 'Kambei Shimada'),
  (50, 16, 'Shichiroji'),
  (51, 17, 'John Doe'),
  (52, 18, 'George Bailey'),
  (53, 18, 'Mary Bailey'),
  (54, 19, 'Dr. Hannibal Lecter'),
  (55, 19, 'Clarice Starling'),
  (56, 20, 'Private James Ryan'),
  (57, 20, 'Technical Sergeant'),
  (58, 21, 'Buscapé'),
  (59, 21, 'Zé Pequeno'),
  (60, 22, 'Guido Orefice'),
  (61, 22, 'Dora'),
  (62, 23, 'John Coffey'),
  (63, 23, 'Warden'),
  (64, 24, 'Cooper'),
  (65, 24, 'Brand'),
  (66, 24, 'Murph'),
  (67, 25, 'Chihiro'),
  (68, 26, 'Kim Ki-taek'),
  (69, 26, 'Mr. Park'),
  (70, 26, 'Chung-sook'),
  (71, 27, 'Léon'),
  (72, 27, 'Mathilda'),
  (73, 28, 'Verbal Kint'),
  (74, 28, 'Mysterious Operative'),
  (75, 29, 'Harakiri Master'),
  (76, 30, 'Simba (voice)'),
  (77, 30, 'Mufasa (voice)'),
  (78, 31, 'Marty McFly'),
  (79, 31, 'Doc Brown'),
  (80, 31, 'Lorraine Baines'),
  (81, 32, 'Władysław Szpilman'),
  (82, 33, 'The Terminator'),
  (83, 33, 'Sarah Connor'),
  (84, 34, 'Maximus'),
  (85, 34, 'Commodus'),
  (86, 36, 'Sergeant Dignam'),
  (87, 37, 'Robert Angier'),
  (88, 38, 'Andrew Neiman'),
  (89, 38, 'Terence Fletcher'),
  (90, 39, 'Philippe'),
  (91, 39, 'Driss'),
  (92, 40, 'Wiesler'),
  (93, 41, 'Seita'),
  (94, 41, 'Setsuko'),
  (95, 42, 'Rick Blaine'),
  (96, 42, 'Ilsa Lund'),
  (97, 43, 'Alfredo'),
  (98, 43, 'Village Elder'),
  (99, 44, 'Ellen Ripley'),
  (100, 56, 'Tony Stark/Iron Man');

CREATE TABLE IF NOT EXISTS Users        
(
    id int AUTO_INCREMENT PRIMARY KEY,
    username NVARCHAR(64) NOT NULL UNIQUE,
    password NVARCHAR(64) NOT NULL,
    salt NVARCHAR(4096) NOT NULL,
    role ENUM('Admin','Plus') NOT NULL
    
)            
        